baseURL = "https://nicstats.netlify.app/"
languageCode = "en-us"
title = "Nic Stats"

theme = "wyrfraym"

enableRobotsTXT = true

[related]
    threshold = 0 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "date"
        weight = 10


reading_time = true

#[[menu.footer]]
  #name = "About"
  #url = "/about"


#[[menu.footer]]
 # name = "contact me"
  #url="/contact" 

[params]
    description = "My site description"

[[menu.main]]
    name = "Get in touch"
    url = "/contact"

preserveTaxonomyNames = true

